version: '3.1'

services:

  mongo:
    image: mongo
    container_name: games-store
    restart: always
    environment:
      MONGO_INITDB_DATABASE: games-store-db
    ports:
      - "27017:27017"
    volumes:
      - ./dbInit.mongodb.js:/setup/dbInit.mongodb.js
